version: '3.8'

services:

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./certs:/var/lib/postgresql/certs
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    command: [ "postgres", "-c", "config_file=/etc/postgresql/postgresql.conf" ]

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  device-registration-service:
    build: ./device-registration-service
    image: balakummithi/device-registration-service:1.0
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?ssl=true&sslmode=require
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    #ports:# No ports exposed â†’ internal-only
    #  - "8091:8091"

  device-statistics-service:
    build: ./device-statistics-service
    image: balakummithi/device-statistics-service:1.0
    depends_on:
      - postgres
      - device-registration-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}?ssl=true&sslmode=require
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      DEVICE_API_URL: http://device-registration-service:8091
    ports:
      - "8092:8092"

volumes:
  postgres_data:
