spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}?ssl=true&sslmode=require
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

device:
  api:
    url: http://localhost:8091
server:
  port: 8092
