spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

device:
  api:
    url: ${DEVICE_API_URL}
server:
  port: 8092
