apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-registration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: device-registration-service
  template:
    metadata:
      labels:
        app: device-registration-service
    spec:
      containers:
        - name: device-registration-service
          image: balakummithi/device-registration-service:1.0
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
            - name: SPRING_DATASOURCE_USERNAME
              value: ${POSTGRES_USER}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${POSTGRES_PASSWORD}
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: device-registration-service
spec:
  type: ClusterIP # internal only
  selector:
    app: device-registration-service
  ports:
    - port: 8091
      targetPort: 8091
